<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Category;
use App\Models\SubCategory;
use App\Models\AgencyVendor;
use App\Models\Expense;
use Carbon\Carbon;
use Faker\Factory as Faker;

class ExpenseTestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();

        $user = User::first();
        $userId = $user ? $user->id : 1;
        $categories = Category::all();
        $vendors = AgencyVendor::all();
        
        if ($categories->isEmpty()) {
            $this->command->warn('No categories found. Cannot create mock expenses.');
            return;
        }

        if ($vendors->isEmpty()) {
            $this->command->warn('No agency/vendors found. Cannot create mock expenses.');
            return;
        }

        $years = [2025, 2026];
        $months = range(1, 12);

        $this->command->info('Creating mock expenses for 2025 and 2026...');

        $count = 0;
        foreach ($years as $year) {
            foreach ($months as $month) {
                // Create 3 to 6 expenses per month
                $numExpenses = rand(3, 6);
                
                for ($i = 0; $i < $numExpenses; $i++) {
                    $category = $categories->random();
                    $subCategories = SubCategory::where('category_id', $category->id)->get();
                    $subCategoryId = $subCategories->isNotEmpty() ? $subCategories->random()->id : null;
                    $vendor = $vendors->random();

                    // Generate a random day in the month
                    $daysInMonth = Carbon::create($year, $month)->daysInMonth;
                    $day = rand(1, $daysInMonth);
                    $expenseDate = Carbon::create($year, $month, $day)->format('Y-m-d');

                    Expense::create([
                        'user_id' => $userId,
                        'expense_category_id' => $category->id,
                        'expense_sub_category_id' => $subCategoryId,
                        'agency_vendor_id' => $vendor->id,
                        'name' => 'Mock Expense ' . $faker->word(),
                        'amount' => rand(1000, 20000) + (rand(0, 99) / 100),
                        'note' => 'Generated by ExpenseTestSeeder',
                        'expense_date' => $expenseDate,
                    ]);
                    $count++;
                }
            }
        }
        
        $this->command->info("Successfully seeded {$count} expenses across 2025 and 2026.");
    }
}
