<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\AgencyVendor;
use App\Models\Payment;
use Carbon\Carbon;
use Faker\Factory as Faker;

class PaymentTestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();

        $user = User::first();
        $userId = $user ? $user->id : 1;
        $vendors = AgencyVendor::all();
        
        if ($vendors->isEmpty()) {
            $this->command->warn('No agency/vendors found. Cannot create mock payments.');
            return;
        }

        $years = [2025, 2026];
        $months = range(1, 12);

        $this->command->info('Creating mock payments for 2025 and 2026...');

        $count = 0;
        foreach ($years as $year) {
            foreach ($months as $month) {
                // Create 3 to 6 payments per month
                $numPayments = rand(3, 6);
                
                for ($i = 0; $i < $numPayments; $i++) {
                    $vendor = $vendors->random();

                    // Generate a random day in the month
                    $daysInMonth = Carbon::create($year, $month)->daysInMonth;
                    $day = rand(1, $daysInMonth);
                    $paymentDate = Carbon::create($year, $month, $day)->format('Y-m-d');

                    $payment = Payment::create([
                        'user_id' => $userId,
                        'agency_vendor_id' => $vendor->id,
                        'amount' => rand(100, 5000) + (rand(0, 99) / 100),
                        'payment_type' => rand(0, 1),
                        'notes' => 'Mock Payment ' . $faker->word() . ' Generated by PaymentTestSeeder',
                        'payment_date' => $paymentDate,
                    ]);
                    
                    $bal = \App\Services\SyncBalance::updateBalance($vendor->id, $payment->amount, 'payment', 'add', $payment->payment_type);
                    \Carbon\Carbon::setTestNow(\Carbon\Carbon::parse($paymentDate)->addHours(rand(8,17)));
                    \App\Services\VendorLedgerService::addEntry($payment, $vendor->id, $payment->amount, 'payment', $bal, 'Payment Added', $payment->payment_type);
                    \Carbon\Carbon::setTestNow();
                    $count++;
                }
            }
        }
        
        $this->command->info("Successfully seeded {$count} payments across 2025 and 2026.");
    }
}
