<!DOCTYPE html>
<html>
<head>
    <title>Weekly Financial Report</title>
</head>
<body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
    <div style="max-width: 600px; margin: 0 auto; border: 1px solid #ddd; padding: 20px; border-radius: 8px;">
        <h2 style="color: #4f46e5; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">Weekly Financial Report</h2>
        
        <p>Hello,</p>
        <p>Here is the financial summary for the week of <strong>{{ $reportData['start_date'] }}</strong> to <strong>{{ $reportData['end_date'] }}</strong>.</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <tr>
                <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Total Expenses</td>
                <td style="padding: 10px; border: 1px solid #ddd; text-align: right; color: #dc2626;">{{ number_format($reportData['expenses'], 2) }}</td>
            </tr>
            <tr>
                <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Total Payments</td>
                <td style="padding: 10px; border: 1px solid #ddd; text-align: right; color: #16a34a;">{{ number_format($reportData['payments'], 2) }}</td>
            </tr>
            <tr style="background-color: #f3f4f6;">
                <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold; font-size: 1.1em;">Final Amount (Payments - Expenses)</td>
                <td style="padding: 10px; border: 1px solid #ddd; text-align: right; font-weight: bold; font-size: 1.1em;">{{ number_format($reportData['final_amount'], 2) }}</td>
            </tr>
        </table>
        
        <p style="margin-top: 30px; font-size: 0.9em; color: #666;">This is an automated report generated by the application.</p>
    </div>
</body>
</html>
